### ISSUE TITLE
Typo in main.cpp

### ISSUE THREAD

**Issue by vifi42** [normen/arduino-433#1]
Hey,
I think there was a little Typo in Lin46 in main.cpp. When working with the Library by Little Satan I think it should be:
#include <ELECHOUSE_CC1101_SRC_DRV.h>

https://github.com/normen/arduino-433/blob/7825494ad5e6b046e736a6fe72946d91e0759116/src/main.cpp#L46

**Comment by normen** [comment]
Nah, actually the library was changed, it used to be RCS 🙂 

I knew I should have put a specific commit in the library entry... But it looks like he cleaned up the library to be compatible with the arduino library manager, maybe he put it in there and I don't have to use the github anymore... I'll check asap, thanks for reporting!

**Comment by normen** [comment]
Yep, as I expected. The new version 1.1 uses the library manager now. Much better. Thanks again.
