### ISSUE TITLE
error in code order

### ISSUE THREAD

**Issue by charliejgallo** [normen/arduino-433#2]
compiled and nothing happened (esp8266 and cc1101)...

looking at https://github.com/LSatan/SmartRC-CC1101-Driver-Lib says that "ELECHOUSE_cc1101.Init(); //Initialize the cc1101. Must be set first!" 

and in the code "ELECHOUSE_cc1101.setRxBW(16); and ELECHOUSE_cc1101.setMHZ(433.92); " are set before that.

 changed the order, initialized "ELECHOUSE_cc1101.Init();" first and now everything works.

**Comment by normen** [comment]
> compiled and nothing happened (esp8266 and cc1101)...
>
> looking at https://github.com/LSatan/SmartRC-CC1101-Driver-Lib says that "ELECHOUSE_cc1101.Init(); //Initialize the cc1101. Must be set first!" 
>
> and in the code "ELECHOUSE_cc1101.setRxBW(16); and ELECHOUSE_cc1101.setMHZ(433.92); " are set before that.
>
>  changed the order, initialized "ELECHOUSE_cc1101.Init();" first and now everything works.  
>
Thanks
