### ISSUE TITLE
Fix for using RC-Switch

### ISSUE THREAD

**Issue by mikeMikeymike** [normen/arduino-433#5]
I'm using the Arduino IDE to program my D1 Clone. ESPiLight didn't recognize my buttons (wireless GE Doorbell button), so I have to use Rc-Switch.

It wasn't printing out the code to the serial port until I changed this line in receiveRcData().
Old line:
`String out = value + dash + pulse + dash + protocol;`
New line:
`String out = String(value) + dash + pulse + dash + protocol;`
Apparently the value variable wasn't being converted to a string.

**Comment by normen** [comment]
Funny, as the pulse should also be an int... But I suppose String-ifying everything just for safety might be a good idea.. I'll keep this open, maybe you get around doing a PR? Otherwise I'll add the change next time I dive into this code.

**Comment by mikeMikeymike** [comment]
I've never done anything like a pull request. Just tried it and hope it worked?

**Comment by normen** [comment]
Heh, no there doesn't seem to be a new incoming PR but no worries, I'll get around to it.

**Comment by normen** [comment]
fixed in latest version 1.2.1
